name = "CodeCells"
uuid = "c2e51c86-72c7-4976-a698-305ddf5ed7c9"
version = "0.1.0"
authors = ["Mason Protter <mason.protter@icloud.com>"]

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
MakieExt = "Makie"
PlotsExt = "Plots"

[compat]
Revise = "3.8.1"
