name = "CodeCells"
uuid = "c2e51c86-72c7-4976-a698-305ddf5ed7c9"
version = "0.1.0"
authors = ["Mason Protter <mason.protter@icloud.com>"]

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
MakieExt = "Makie"
PlotsExt = "Plots"

[compat]
FileWatching = "1.10"
julia = "1.10"
